- name: Install MariaDB-Server
  yum: pkg=mariadb-server state=present
  tags: database
- name: Install MariaDB-client
  yum: pkg=mariadb state=present
  tags: database
- name: install MySQL-python pkg
  yum: pkg=MySQL-python state=present
  tags: database
- name: start and enable MariaDB-Server
  service: name=mariadb state=restarted enabled=yes
  tags: database
- name: pause to build database cache 
  pause: seconds=10
  ignore_errors: yes
  tags: database
- name: Check if the root password is previously set or NOT
  shell: mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
- debug: var=root_pwd_check
  tags: database
- name: Set MariaDB root password for the first time
  mysql_user: name=root password={{ mysql_root_password }} host=localhost state=present
  ignore_errors: yes
  tags: database
- name: Remove The Annynmous User
  mysql_user: name='' login_user=root login_password={{ mysql_root_password }} host=localhost state=absent
  ignore_errors: yes
  tags: database
- name: Remove The Test Database
  mysql_db: name=test state=absent login_user=root login_password={{ mysql_root_password }} 
  ignore_errors: yes      
  tags: database
- name: Creating wordpress DB with the Root User
  mysql_db: name={{ wordpress_db }} state=present login_user=root login_password={{ mysql_root_password }}
  ignore_errors: yes
  tags: database
- name: Creating wordpress user and give him all privileges on wordpress db
  mysql_user: name={{ wordpress_dbuser }} host=localhost password={{ wordpress_dbpass }} state=present priv={{ wordpress_db }}.*:ALL  login_user=root login_password={{ mysql_root_password }}
  ignore_errors: yes
  tags: database
